name: Python autotests

# on: [push]
on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        type: choice
        default: second_test
        options:
          - first_test
          - second_test
#          - smoke
#          - regression
#          - extended
#          - all

jobs: 
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests # Название джобы
    steps: # Шаги начинаются с тире
      - name: Checkout autotests # Название шага
        uses: actions/checkout@v5 # Вводим actions/checkout@v5 в гугле и смотрим на github актуальную версию
      - name: Set up Python environment
        uses: actions/setup-python@v6 # Вводим actions/setup-python@v2 в гугле и смотрим на github актуальную версию
        with:
          python-version: '3.13'
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: first_test
        run: pytest
      - name: second_test
        run: pytest
